### ISSUE TITLE
Соблюдение стандартов

### ISSUE THREAD

**Issue by Azmodan95** [unpredictable-username/toxin-hotel-booking-website#35]
https://github.com/unpredictable-username/toxin-hotel-booking-website/blob/f0d68c6335aa051203ae32130a16bbfa2dd3ba41/src/components/counter/counter.ts#L53
Пункт [5.1](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#5.1) Все классы, которые используем для поиска по DOM-у должны начинаться с префикса js-

**Comment by Azmodan95** [comment]
У тебя есть блок cards в который вложены другие блоки с карточками регистрации, логина и т.д. Нужно их вынести в самостоятельные блоки пункт [4.2](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.2).

**Comment by a-poluhin** [comment]
> Пункт 5.1 Все классы, которые используем для поиска по DOM-у должны начинаться с префикса js-

![image](https://user-images.githubusercontent.com/10168007/101772274-bb748c80-3b1d-11eb-8715-8c9e22ba3fdf.png)
остались еще места глянь по проекту

**Comment by a-poluhin** [comment]
Можно закрывать.
