### ISSUE TITLE
Название имени блока

### ISSUE THREAD

**Issue by Azmodan95** [unpredictable-username/toxin-hotel-booking-website#45]
https://github.com/unpredictable-username/toxin-hotel-booking-website/blob/d8c8b25d34868f9c4a6e7fbe6a02024de6660797/src/components/calendar/calendar.pug#L2 Название имени блока должно соответствовать названию миксина, то есть если у тебя миксин назван calendar, то и блок должен называться calendar. То есть в данном случае сначала должен идти класс calendar, а потом уже calendar__container.

**Comment by a-poluhin** [comment]
Это можно закрывать
