### ISSUE TITLE
Модификаторы элементов БЭМ

### ISSUE THREAD

**Issue by Azmodan95** [unpredictable-username/toxin-hotel-booking-website#48]
https://github.com/unpredictable-username/toxin-hotel-booking-website/blob/a0aeb7eb4ecf6468a31d4165eac68c1601d1517f/src/components/menu/menu.scss#L22
Если используются модификаторы [ключ-значение](https://ru.bem.info/methodology/quick-start/#%D0%BA%D0%BB%D1%8E%D1%87-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5), то должно идти сначала имя модификатора и только потом его значение, у тебя же сразу идет его значение, подобное допустимо только при булевых модификаторах, в данном случае должно быть как-то так `.menu__item_type_expandable`.

**Comment by a-poluhin** [comment]
Можно закрывать
